### ISSUE TITLE
Support: Can't run on port 80

### ISSUE THREAD

**Issue by JayHoltslander** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#1]
Followed all the directions both here in the readme as well as consulted the included documentation.html

App cloned to and runs in the root of MAMP's htdocs folder.
App runs fine at localhost:8888 (see below re: port 80)
App's "Requirements Analyzer" running on port 8888 reports everything in the green.
Clicking step 1's "Continue" button results in the URL "http://localhost/?step=verify" being loaded with the error "Safari can't connect to the server. Safari can't open the page "http://localhost/?step=verify" because Safari can't connect to the server "localhost"."
If I manually change the address to "localhost:8888/?step=verify" I see the screen that I'm supposed to, asking me to confirm settings. However every item there has an error "Undefined variable"

Changed MAMPs preferences to use Apache port 80 Nginx port 80 MySQL 3306, (As recommended) Restarted MAMP.

MAMP tries to open http://localhost/ but serves error page: "Not Found. The requested URL / was not found on this server."

**Comment by JayHoltslander** [comment]
My hosts file content:

    ##
    # Host Database
    #
    # localhost is used to configure the loopback interface
    # when the system is booting.  Do not change this entry.
    ##
    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost 
    fe80::1%lo0	localhost

**Comment by michelve** [comment]
Note: please make sure to have the latest version running

Try turning off the default mac apache by executing this in your terminal 
sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist

then restart your mac when the recommend ports

After you have tried the above steps open the web app and point to your index,php file ex: http://localhost/index.php and follow the install guide

let me know if this helps. Also i recommend you to create your own virtual host for the app to avoid any issues

**Comment by JayHoltslander** [comment]
>Try turning off the default mac apache by executing this in your terminal 
>sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist

    launchctl: Error unloading: org.apache.httpd 
(OS X 10.9.5)

**Comment by michelve** [comment]
launchctl: is shown because apachectl is using launchd's control script, launchctl, to start and stop Apache.

Error unloading means the given daemon/service of launchd can not be stopped. This usually happens if the given daemon is already stopped.

org.apache.httpd is the name of the plist file defining how httpd is run by launchd. If you are curious the actual plist is at

/System/Library/LaunchDaemons/org.apache.httpd.plist

i have created a wiki page for this topic 
https://github.com/michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-/wiki/Getting-port-80-to-work-with-MAMP

**Comment by JayHoltslander** [comment]
I have gotten it working now. 
However after the site and the database are successfully created and MAMP restarted, attempting to launch the wp site results in "http://createdsite.dev" opening ok, but loading your web app instead of the wordpress install at "htdocs/createdsite.com/"

**Comment by michelve** [comment]
do you have the app files inside that folder (createdsite.com)? what i recommend is yo create a another site called wp.com (wp.dev/) and put the web app inside there it will prevent nay future conflict.

**Comment by JayHoltslander** [comment]
@michelve Your web app files located at:
    Applications/MAMP/htdocs/
Install through web app located at:
    Applications/MAMP/htdocs/createdsite.com/

"localhost/" displays web app
"createdsite.dev" (files located at Applications/MAMP/htdocs/createdsite.com/) also displays web app.

**Comment by michelve** [comment]
@JayHoltslander if you want can do a little remote session and i can trouble shoot your issue http://download.teamviewer.com/download/TeamViewerQS.dmg here is my email address mvelis90 at gmail dot com

**Comment by JayHoltslander** [comment]
Replied via email asking when works for you.

**Comment by michelve** [comment]
@JayHoltslander im available for the next 25 mins send me your teamviwer pass and id to my email
