### ISSUE TITLE
Local Host Fail

### ISSUE THREAD

**Issue by mkornegay2** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#2]
Michel, there is an issue with localhost when running web app during verify. It tries to verify localhost for WP Install but does not look for localhost:8888. I'm not sure if this is a code error or something I have setup different. I use MAMP defaults other than root folder for sites.

**Comment by michelve** [comment]
thanks for the feedback @mkornegay2  could you be a little more specific about this issue and/or maybe could post some screenshots of the error. Thanks.

**Comment by mkornegay2** [comment]
This is what I get after bypassing the localhost screen. I have to add 8888 after localhost. But the WP DB does not set up correctly. I do not get the screen that is in your video tut. ![screen shot 2015-07-13 at 1 54 24 pm](https://cloud.githubusercontent.com/assets/13319405/8660244/ce5124d8-297d-11e5-9346-c6bfab8270cc.png)

**Comment by michelve** [comment]
@mkornegay2 if you want can do a little quick remote session and i can trouble shoot your issue http://download.teamviewer.com/download/TeamViewerQS.dmg here is my email address mvelis90 at gmail dot com

**Comment by mkornegay2** [comment]
Hi, Michel. I sent you a email yesterday. Can you let me know if you got it? It is regarding yesterday. I cannot access my old site after the install. Need a way to access it or how I can transfer to web app. Thx.

**Comment by michelve** [comment]
@mkornegay2  simple create a new site with the same name using the app and move the old site files inside the new folder(site) then go to phpmyadmin and change the admin url and the home url to point to ur new location

**Comment by mkornegay2** [comment]
Ok. That's what I was hoping. What about creating the new DB on setup. Since I already have one and it's the one that is on my live site I would like to keep it the same. What do I do here?

**Comment by michelve** [comment]
just point your database inside wp-config file to the right address and you should be set

**Comment by mkornegay2** [comment]
Ok. So as long as my wp-config.php file reflects the proper DB changes I should be ok. That is the only file I need to worry about?. WP seems easy at times, but I don't do a lot of localhost sites and transfers enough to remember the process. This is new to me b/c I usually work from the web. Local is faster and keeps me from breaking my site when updating. Just a hassle to keep synced up b/c I make changes to the site that I don't update on the localhost. I know that with DB tables you can really screw up stuff like posts, and historical data if everything is not changed properly. I use a search and replace tool to help make the changes. I'm still uncertain as to the files that have to be edited manually. I guess wp-config points to the DB, the DB points to the table info and the table info points to the site. I know it's not as easy as copying files via FTP like it is with HTML sites. Just trying to get questions answered ahead of time. thx.

**Comment by michelve** [comment]
the only files u have to edit to make the transfer to the new localhost is wp-config

define( 'DB_NAME', 				'dname_here' );
define( 'DB_USER', 				'user_here' );
define( 'DB_PASSWORD', 			'pass_here' );
define( 'DB_HOST', 				'yourNewLocalHost:0000' ); //use the port number

then search inside the php admin for your database and change the old localhost address to the new one 


as far site migration take a look into wp-cli http://wp-cli.org/

**Comment by mkornegay2** [comment]
So when I go to setup the install for the new site via your app, I don't need to install WP again since I'm copying over the files from the other folder which already contains WP?

As for localhost, your are referring to the siteurl under wp_options in my DB, correct?

**Comment by mkornegay2** [comment]
When replacing my db table references, what do I use for siteurl or in the replace string? Do I put http://localhost:8888/mysite.com or .dev? Or should it be 127.0.0.1:8889. I am confused as what is the local host name when using your app because it appends .com on the folder, but says .dev in the url and the DB_Host is 127.0.0.1:8889 instead of LOCALHOST in the wp-config.php file. I have transferred files. I can access site, but it's all messed up. It's not connecting to the DB properly.

**Comment by michelve** [comment]
email me in 10 mins ur teamviewer password and id

**Comment by mkornegay2** [comment]
Bout to be in a meeting. Will do when I get back.

**Comment by mkornegay2** [comment]
Are you still available?

Matt
