### ISSUE TITLE
Feature req. - Themes

### ISSUE THREAD

**Issue by JayHoltslander** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#4]
Would be nice little bonus feature if the app could be reskinned easily perhaps with a [Bootswatch theme](https://bootswatch.com) or just the source Less or Sass included.

**Comment by michelve** [comment]
you mean like been able to switch themes colors inside the app?

**Comment by JayHoltslander** [comment]
That'd be nice. But even better if I could build my own theme from included
less or sass source files.

**Comment by michelve** [comment]
thanks for the input, i like the idea of changing the skin or theme for the app. This is something is something i will definitely add in the near future, but before i have to finish some minor things and add-ons i want to add to the app. Right now im working in a feature called site-migration where you will be able to push your sites to production and im also finishing the back-up tool i released in the previous build.

**Comment by JayHoltslander** [comment]
Those definitely sound better/higher priority than custom skinning the UI. :-)

**Comment by JayHoltslander** [comment]
This migration feature you mention... Will it utilize the [wp-sync-db](https://github.com/wp-sync-db/wp-sync-db) and [wp-sync-db-media-files](https://github.com/wp-sync-db/wp-sync-db-media-files) plugins? :-) I've been using those for a while and am loving them.

**Comment by michelve** [comment]
for the files migration im using the php ftp function that is built in, for the database i may thinking using something similar.
