### ISSUE TITLE
Seemingly conflicting messages

### ISSUE THREAD

**Issue by JayHoltslander** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#5]
Seemingly conflicting messages. (Error/Success.)
![error](https://cloud.githubusercontent.com/assets/2069960/9740840/b078e8dc-560b-11e5-8b17-801653451d19.png)

**Comment by JayHoltslander** [comment]
Also... some form validation to prevent using "-" in a database name would be nice. 
(Or changing "-" to "_")

**Comment by michelve** [comment]
Thanks for the feedback @JayHoltslander - all this issues have been resolved in the beta version, under the dev branch. New ui and major improvements to ui and validation and user flow, any feedback is appreciated
