### ISSUE TITLE
Feedback: Site manager - Listing

### ISSUE THREAD

**Issue by JayHoltslander** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#6]
This seems odd to me.
<img width="1086" alt="zipfile" src="https://cloud.githubusercontent.com/assets/2069960/9749714/7faca87c-5644-11e5-8504-15a9d6cc45cb.png">

**Comment by michelve** [comment]
thanks i will look into this

**Comment by michelve** [comment]
@JayHoltslander - this issue has now been resolved, you can get latest form the master branch
