### ISSUE TITLE
Does it works with Mamp PRO?

### ISSUE THREAD

**Issue by dimitrilongo** [michelve/WordPress-MAMP-Wordpress-Install-Web-Interface-#8]
Hello,
Just discover your app, i'm trying to get it work with mamp pro, i follow all your steps, the difference is i have to create a host in mamppro  like wpapp and set the folder to bin/mamp/wpapp/ so it works i have all check to green, i create a new website, it works also, it asks me to restart Mamp, i did, but the the only issue the script haven't created the new host in mamp pro, If i create a host with the folder of the new website just created with your app it works, i can go to wp-admin .

So i don't know if i done something wrong or just an issue with mamp pro(v3,4 and El Capitan OS)

Thanks a lot for your help
Dimitri

**Comment by michelve** [comment]
hello @dimitrilongo. Thanks for trying the app. No it has not been tested in MAMP PRO since it is not needed, since it was meant to replace it. I might make it work with mamp pro in the future.

**Comment by dimitrilongo** [comment]
thanks for clarification.
